# Generated by Django 4.2.7 on 2024-02-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approved_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_salary',
            field=models.IntegerField(default=0),
        ),
    ]
