# Generated by Django 4.2.7 on 2024-02-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_customer_approved_limit_customer_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
