# Generated by Django 4.2.7 on 2024-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0003_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
